version: '3.7'
services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: mentorship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - backend

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es01
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  server:
    build:
      context: mentorship-backend
    container_name: server
    environment:
      POSTGRES_HOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - backend
      - frontend

  client:
    build:
      context: mentorship-client
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    container_name: client
    ports:
      - 3000:80
    restart: always
    depends_on:
      - server
    networks:
      - frontend

volumes:
  pg-data:
  data01:
    driver: local

networks:
  backend:
  frontend:
  elastic:
    driver: bridge
